
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: deploytest2
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 8080
  liveness:
    path: /deploytest2/internal/isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 5
  readiness:
    path: /deploytest2/internal/isReady
    initialDelay: 30
    periodSeconds: 5
    failureThreshold: 5
  resources:
    requests:
      cpu: 200m
      memory: 164Mi
    limits:
      cpu: 600m
      memory: 312Mi
  ingresses:
    - https://app-q1.adeo.no/deploytest2
  replicas:
    min: 4
    max: 4
  env:
    - name: RND_FILE_NAME
      value: "{{ RND_FILE_NAME }}"