name: Build, push, and deploy

on: [push]

env:
  IMAGE: ghcr.io/${{ github.repository }}/deploytest2app1:${{ github.sha }}
  CI: true
  TZ: Europe/Oslo

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish App1 image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${IMAGE} src
          docker push ${IMAGE}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Create random
        run: echo RND_FILE_NAME=$(echo $RANDOM | md5sum | head -c 8) >> $GITHUB_ENV
      - name: Deploy App1 to Q1
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
          CLUSTER: dev-fss
          RESOURCE: nais.yaml
          VAR: RND_FILE_NAME=${{env.RND_FILE_NAME}}